version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  labels:
  - dependencies
  groups:
    all-minor-patch:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
    all-major:
      patterns:
      - '*'
      update-types:
      - major
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 3
  labels:
  - dependencies
  - github-actions
  groups:
    actions-all:
      patterns:
      - '*'
